version: '3.8'

services:
  comercio-app:
    build: .
    container_name: sigcomercio
    ports:
      - "4001:80"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
