version: '3.8'

services:
  comercio-app:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: https://llcsurlorwkvfmbtptko.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_TxwQEid06MuHHFVVd8ZhGw_z1PNGSTE
    container_name: sigcomercio
    ports:
      - "4001:80"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
